### PR TITLE
ipq806x/dsa: enable assisted learning on dsa cpu port

### PR DESCRIPTION
**Pull request by ddimension**
Enable the already existing framework for assisted learning.
Without, there are issues with roaming between switch ports and cpu port.

### CODE REVIEW

**Comment by Ansuel** [comment]
Is assisted learning supported on 5.4?

**Comment by ddimension** [comment]
> Is assisted learning supported on 5.4?

It is patched  into the kernel since 5.4. Take a look here:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=920eaab1d8179035d0ae1047e75cf9a50da6a6eb

I did not compile it for 5.4, but there shouldn't be any difference.

**Comment by Ansuel** [comment]
Nice! Can I include this in the DSA pr?

Il Ven 6 Ago 2021, 23:48 ddimension ***@***.***> ha scritto:

**Comment by ddimension** [comment]
> Nice! Can I include this in the DSA pr? Il Ven 6 Ago 2021, 23:48 ddimension ***@***.***> ha scritto:

Please do so! I couldn't wish more :+1:

**Comment by Ansuel** [comment]
@ddimension sorry for being annoying, can you put your SoB tag in the commit so i can merge 
Also i would rename this 096-35?
Would be also good to say that the required changes are already backported for mvebu target and are only required to be enabled for qca8k

**Comment by ddimension** [comment]
> @ddimension sorry for being annoying, can you put your SoB tag in the commit so i can merge
> Also i would rename this 096-35?
> Would be also good to say that the required changes are already backported for mvebu target and are only required to be enabled for qca8k

Hi!

Of course. But please also do a check. It seems on boot for the first 1-2 minute there's something like a block from lan to cpu. After the network is started. Later it works.

**Comment by Ansuel** [comment]
I notice there are some proposed patches about assisted learning. Could
that be the fix for the initial breakage ?

Il giorno dom 8 ago 2021 alle ore 12:19 ddimension ***@***.***>
ha scritto:

**Comment by ddimension** [comment]
Let's wait for the kernel ml.

**Comment by ddimension** [comment]
I justed testet the patched on netdev. It seems that we are to much behind upstream for this fix. Damn. It will take me some time to backport it.

**Comment by Ansuel** [comment]
I also tried to bsckport but I reached a point where I had like 400kb of
patch to bsckport and I giveup...

Il Mar 10 Ago 2021, 19:03 ddimension ***@***.***> ha scritto:

**Comment by ddimension** [comment]
Oh, bad news:-( So it seems it can't be fixed with 5.10. Do you have an idea? I don't want to imagine what a port to 5.14 means.

ATM I can live with the half working assisted learning - better than nothing. But I won't give it any non-dev.

**Pull request closed without merging**
